# Obsidian to Grafana Configuration
vault_path: "/Users/nic/NVDH Dropbox/Nicole van der Hoeven/DownloadMyBrain"  # Update this to your actual vault path
output_file: "./logs/obsidian_logs.json"
log_level: "INFO"
