global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'obsidian-metrics'
    static_configs:
      - targets: ['metrics-exporter:8080']
    scrape_interval: 30s
    metrics_path: '/metrics'
