apiVersion: 1

datasources:
  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    isDefault: true
    editable: true
    jsonData:
      maxLines: 1000
      derivedFields:
        - datasourceUid: loki
          matcherRegex: ".*"
          name: "Logs"
          url: "/explore?orgId=1&left={\"datasource\":\"loki\",\"queries\":[{\"expr\":\"{job=\\\"obsidian-parser\\\"}\",\"refId\":\"A\"}],\"range\":{\"from\":\"now-1h\",\"to\":\"now\"}}"
    version: 1
